### ISSUE TITLE
DaggerCoreComponent class missing

### ISSUE THREAD

**Issue by ClaudeHangui** [karntrehan/Posts#10]
Hi,
I'm a newbie in using DI with Dagger and I just ran into your article in medium which brought me here.
I can't find the DaggerCoreComponent class which is used to instantiate the CoreComponent interface.

**Comment by karntrehan** [comment]
Hie. The `DaggerCoreComponent` class is auto-generated at compile time. Please build the project once and it should be generated.

**Comment by ClaudeHangui** [comment]
Thanks....re-building the project indeed solved the issue !
