### ISSUE TITLE
Custom SharedPref module

### ISSUE THREAD

**Issue by ClaudeHangui** [karntrehan/Posts#11]
Hi,
I'd like to construct a shared preference with a name. I made a module which injects the app context as you did, and I initialised the SharedPreference object in there. I want my shared preferences to be created (if desired) with a pref name
Problem is when I build the project, I run into this error:

Error:(20, 34) error: SharedPreferenceHelperModule cannot be provided without an @Inject constructor or from an @Provides-annotated method.

Here is my module class:
`
    @Module
    public class SharedPreferenceHelperModule
    {
        private String mPrefName;
        private SharedPreferences sharedPreferences;

    public void setPrefName(String mPrefName) {
        this.mPrefName = mPrefName;
    }

    public String getPrefName() {
        return mPrefName;
    }

    @Provides @Singleton
    SharedPreferences provideSharedPreference(Application mContext) {
        if (getPrefName() != null)
            sharedPreferences = mContext.getSharedPreferences(getPrefName(), Context.MODE_PRIVATE);
        return PreferenceManager.getDefaultSharedPreferences(mContext);
    }
}`

**Comment by karntrehan** [comment]
Creating a Module for a single SharedPreference is kind of over-engineering according to me. You can still execute this by changing  `provideSharedPreference(Application mContext)` to `provideSharedPreference(Context mContext)`

**Comment by ClaudeHangui** [comment]
Ok ...I hear you ! it's better to inject SharedPref in already existing module instead of creating a module just for this...
Which brings me to the question: **when do I need to create a module ??**

**Comment by karntrehan** [comment]
A module is created whenever you want to provide elements of a particular context. Eg - the `NetworkModule` provides all the dependencies related to the networking context. 

As this is not an issue with the project, I am closing the issue.
