### ISSUE TITLE
Gradle build failure

### ISSUE THREAD

**Issue by bcalendreau** [karntrehan/Posts#12]
Hello,

I cloned and imported the project to Android Studio (the latest version) and had to the build tools version to 27.0.3 and Android Plugin to 3.1.2

I created as well a new supportLibrary variable for the build to 27.1.1

I can't build the project as I run into this error, which seems to come from an incompatibility with kapt : 

> Folder D:\Downloads\Posts\core\build\generated\source\kaptKotlin\debug
> Folder D:\Downloads\Posts\core\build\generated\source\kaptKotlin\release
> Folder D:\Downloads\Posts\posts\build\generated\source\kaptKotlin\debug
> Folder D:\Downloads\Posts\posts\build\generated\source\kaptKotlin\release
> 
> 3rd-party Gradle plug-ins may be the cause

Maybe an update of the dependencies is required ? I searched quite a bit but couldn't make it work.

Thanks !

**Comment by karntrehan** [comment]
Hie,
I updated the versions to the libraries and was able to build successfully. Maybe a "Clean" and "Rebuiild" of the project would help? 

Also, you will have to update the Adapters (List & Details) a bit as the support library changes the Create and Bind ViewHolder function parameters to non-nulls hence showing us an error. 

Do let me know if you need any more help.

**Comment by bcalendreau** [comment]
Thanks a lot for your reply.
I had runned into some weird issues in the past not launching Android Studio in admin mode.

I tried and now I get another error : 
Posts\posts\build\tmp\kapt3\stubs\debug\com\karntrehan\posts\list\di\ListModule.java:6: error: @Modules cannot be scoped. Did you mean to scope a method instead?
@ListScope()

I had updated the dependencies versions as follow : 

> 'buildTools'       : '27.0.3',
> 'supportLibrary'   : '27.0.2',
> 'androidPlugin'    : '3.1.2',
> 'kotlin'           : '1.2.41',
> 'dagger'         : '2.15',

It seems I'm getting there !
Maybe you could to do a push with the new modifications ?
THanks again

**Comment by bcalendreau** [comment]
Sorry for the spam, but with Dagger 2.11 it compiles and runs, so I guess after a few tweakings it'll run perfectly.
And by the way thanks for putting this project online, I absolutely love the whole modulary approach and the quality of the code, which I want to get inspired from for my project.

**Comment by karntrehan** [comment]
Glad I could help. Feel free to close the issue if there are no errors faced by you.
