### ISSUE TITLE
about room database question

### ISSUE THREAD

**Issue by LeonDevLifeLog** [karntrehan/Posts#19]
in this doc([Save data in a local database using Room](https://developer.android.com/training/data-storage/room/index.html?hl=zh-cn#kotlin)) said:
> Note: If your app runs in a single process, you should follow the singleton design pattern when instantiating an AppDatabase object. Each RoomDatabase instance is fairly expensive, and you rarely need access to multiple instances within a single process.

I want to ask is there has performance problem when in modular architecture.

thanks a lot!

**Comment by karntrehan** [comment]
Hie,
I am not sure of this. Must depend on the number of database modules you will have in your app and how often you initialize them. Honestly, I am not so sure.

**Comment by LeonDevLifeLog** [comment]
thanks!
